VKSpammer/VKSpam_djg/urls.py
# -*- coding: utf8 -*-
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views
from django.views.generic import DetailView, ListView
from VKSpam_djg.models import CampParams

app_name='VKSpam_djg'

#в коммуникаторе шаблоны адресов пока ТУТ!!
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$', views.window_for_captcha, name='window_for_captcha'),
    # url(r'^(?P<group_id>[a-zA-Z0-9]+)/statistics/$', views.statistics, name='statistics'),
    # непонятно почему, но символ начала строки не нужен
    url(r'works_with_groups/$', views.works_with_groups, name='works_with_groups'),
    url(r'statistics/$', views.statistics, name='statistics'),
    url(r'distr_to_avas/$', views.distr_to_avas, name='distr_to_avas'),
    url(r'distr_to_walls/$', views.distr_to_walls, name='distr_to_walls',),
    url(r'distr_to_privat/$', views.distr_to_privat, name='distr_to_privat',),
    url(r'captcha_input_form/$', views.captcha_input_form, name='captcha_input_form'),
    # здесь ИМЯ - ИМЯ ПЕРЕМЕННОЙ В ССЫЛКЕ ФОРМЫ В ШАБЛОНЕ!!!
    url(r'sender_bots/$', views.bots_senders_params, name='bots_senders'),
    url(r'get_set_of_tokens/$', views.get_set_of_tokens, name='get_set_of_tokens'),
    url(
        r'make_distribution_to_friends_private/',
        views.make_distribution_to_friends_private,
        name='make_distribution_to_friends_private'
    ),
    url(
        r'make_distribution_to_aim_group_users/',
        views.make_distribution_to_aim_group_users,
        name='make_distribution_to_aim_group_users'
    ),
    url(
        r'make_distribution_in_privat_through_fake_browser/',
        views.make_distribution_in_privat_through_fake_browser,
        name='make_distribution_in_privat_through_fake_browser'
    ),
    # url(r'start_campaign/$', views.start_campaign, name='start_campaign'),
    url(
        r'start_campaign/$',
        ListView.as_view(
            queryset=CampParams.objects.all(),
            context_object_name='campaign_list',
            template_name='VKSpam_djg/set_up_campaigns.html')
    ),
    url(r'working_with_aim_group/$', views.working_with_aim_group, name='working_with_aim_group'),
    url(r'get_aim_group_wall_posts/$', views.get_aim_group_wall_posts, name='get_aim_group_wall_posts'),
    url(r'add_bots_to_eachother_friends/$', views.add_bots_to_eachother_friends, name='add_bots_to_eachother_friends'),
    url(r'like_aim_group_wall_post_through_fake_browser/$',
        views.like_aim_group_wall_post_through_fake_browser,
        name='like_aim_group_wall_post_through_fake_browser'),
    url(r'get_notifications_for_sender_and_sent_to_telegram/$',
        views.get_notifications_for_sender_bots_and_sent_to_telegram,
        name='get_sender_bots_notifications_and_sent_to_telegram')
]

VKSpammer/VKSpammer/urls.py
from django.conf.urls import  include, url
from django.contrib import admin
admin.autodiscover()

# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
# ]

#и тут почему-то. Блин, непонятно
urlpatterns = [#'',
    # here we are not using pattern module like in previous django versions# here we are not using pattern module like in previous django versions
    #Значок доллара в конце не нужен, тк ЭТО КОНЕЦ СТРОКИ!!
    url(r'^VKCommunicator/', include('VKSpam_djg.urls', namespace='VKSpam_djg')),
    #url(r'^VKCommunicator/$', include('VKSpammer.urls', namespace="VKSpammer")),
    #url(r'^VKCommunicator/statistics/$', 'VKSpam_djg.views.statistics'),
    #url(r'^VKCommunicator/(?P<vk_group_id>\d+)/$', 'VKSpam_djg.views.detail'),
    #url(r'^VKCommunicator/(?P<vk_group_id>\d+)/results/$', 'VKCommunicator.views.results'),
    #url(r'^VKCommunicator/(?P<vk_group_id>\d+)/vote/$', 'VKCommunicator.views.vote'),
    url(r'^admin/', admin.site.urls),
]

VKSpammer/VKSpam_djg/views.py
#!/usr/bin/env python3
import sys
import socket
from .private_message_sending_strategyes import *
from selenium.common.exceptions import ElementNotVisibleException as elementNotVisibleException
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import WebDriverException
from .VKCommunicatorExceptions import TooFarLastAutorisationException
from multiprocessing import Process
# добавляем путь, где находится backend с бизнес-логикой
pathWithBuisnessLogic = '/home/grishaev/PycharmProjects/VKSpammer/'
sys.path.append(pathWithBuisnessLogic)

from .private_message_sending_strategyes import *
from .commenters import *
from .telegram_bot import TelegramBot
from django.shortcuts import render,  HttpResponseRedirect
from .forms import CampParamsForm
from .forms import DoCommentPhotoForm
from .forms import GetTokenForm
from .forms import AskTokenForm
from .forms import EnterGroupIdForm
from .forms import EnterCaptchaForm
from .forms import DoPrivatMessageForm
from .forms import GetStatisticsForm
from .forms import DoWallPostForm, GetAvaInfoAndPhotoSettingsForm, GetSetOfTokensForm, AutorisationForm
from .forms import DoPrivatMultisenderSendingMessForm
from .forms import MultisenderGetAvaInfoAndPhotoSettingForm, GetUpdatesOfAimGroupForm, DoCommentPhotoMultisenderForm
from .forms import DoCommentPhotoMustiprocMultisendForm, SendMessagesToAimGroupUserForm
from .forms import AddBotsInEachOtherFriendForm, SendMessagesToFriendsPrivateForm
from .forms import MakeDistributionThroughFakeBrowserForm, GetAimGroupWallPostsForm, LikeAimGroupPostsForm
from _datetime import datetime
from django.utils import timezone
from time import sleep
from work_with_vk_friends import MessageToPrivateSender
from app_info import parse_and_save_auth_params
from app_info import get_token_by_inner_driver, get_auth_params_from_interface, autentification_in_vk_via_web_dr
from app_info import final_sending_privat_message, get_ava_id_and_insert_in_into_db, get_settings_of_photo, \
    many_posts_wall_message
from app_info import final_getting_subscribers_with_offsets_loop
from app_info import get_important_params
from app_info import logger, process_log_file_path
from app_info import final_sending_privat_message_with_multisender
from app_info import multiproc_do_comment_photo, multiproc_get_photo_params
from app_info import add_bots_to_friends_of_each_other
from app_info import get_wall_posts
from app_info import vk_api_version
from app_info import day_ava_message_limit
# from app_info import attachments # todo временное
# from work_with_DB import select_count_have_posted_ava_messages
from work_with_DB import connection_to_postgres
from .models import VkGroupUserUnion2, BotsSenders, CampParams, AvaMessages, VKApplications, GorkiyGroupUser, \
    PrivateMessages, BotsFriends, InvitePrivateMessages, InviteMessagesToLoyalGroupUsers, VkWallPosts
from django.core.exceptions import ObjectDoesNotExist
# from app_info import do_comment_photo
from .selenium_sender import SeleniumSender
from .vk_notifications_api import VkNotifications

# vk_api_version = '5.00'
# proccess_log_file_path =
# '/home/grishaev/PycharmProjects/VKSpammer/VKSpammer/VKSpam_djg/static/VKSpam_djg/process_log.txt'
logger = logging.getLogger('logger_view_communicator')
logger.setLevel(logging.INFO)
# fh = logging.FileHandler(proccess_log_file_path)
# fh.setLevel(logging.INFO)
# logger_for_communicator.addHandler(fh)

# logging.basicConfig(level=logging.INFO)


def index(request):
    context = {}
    if request.method == 'POST':
        logging.info('обработали запрос')
        get_token_form = GetTokenForm(request.POST)
        # ask_token_form = AskTokenForm(request.POST)
        enter_group_id_form = EnterGroupIdForm(request.POST)
        do_comment_photo_form = DoCommentPhotoForm(request.POST)
        enter_captcha_form = EnterCaptchaForm(request.POST)
        do_wall_post_form = DoWallPostForm(request.POST)
        do_privat_message_form = DoPrivatMessageForm(request.POST)

        # logging.debug(get_token_form.is_valid())
        # logging.debug(ask_token_form.is_valid())
        logger.info('{}: '.format(datetime.now(), request.POST))
        print(request.POST)
        if get_token_form.is_valid():
            # process the data in form.cleaned_data as required
            # redirect to a new URL:
            user_token = get_token_form.cleaned_data.get('user_token')
            parsed_token, vk_user_id, expires_in = parse_and_save_auth_params(user_token)
            try:
                sender: BotsSenders = BotsSenders.objects.get(vk_user_id=vk_user_id)
            except BotsSenders.DoesNotExist:
                sender = False
            if sender:
                sender.vk_token = parsed_token
                sender.save()
            logger.info("{} - обработали полученный токен: {}".format(datetime.now(), parsed_token))
            context['result_of_handling_token_string'] = "Токен успешно загружен в программу " + parsed_token
            # return HttpResponseRedirect('/thanks/')
            # elif request.POST.get('ask_token_btn'): хз, но почему-то изменилось ПОСЛЕ ДОБАВЛЕНИЯ CSS((
            # result = request.POST.get('ask_token_btn')#

        elif request.POST.get('take_token'):
            result = request.POST.get('take_token')
            logging.info(result)
            # хардкодим процесс, порождающий рандомное использование нескольких приложений
            vk_app_list = VKApplications.objects.all()
            vk_app_id = vk_app_list.get(id=random.randint(1, len(vk_app_list))).vk_app_id
            if result is not False:  # сознательное дублирование изначального условия
                get_auth_params_from_interface(vk_app_id)

        elif request.POST.get('take_all_token_automatically'):
            request.POST.get('take_all_token_automatically')
            for bot in BotsSenders.objects.all():
                bot.vk_token
                get_token_by_inner_driver(bot.vk_login, bot.vk_password)

        elif enter_group_id_form.is_valid():
            group_id_to_insert = enter_group_id_form.cleaned_data.get('inputed_group_id')
            logging.info(group_id_to_insert)
            api, conn, cur = get_important_params()
            result = final_getting_subscribers_with_offsets_loop(api, group_id_to_insert)
            if result == 'OK':
                context['status_for_getting_subscribers'] = \
                    enter_group_id_form.status_for_getting_subscribers.format(group_id_to_insert)
        # чтобы работать с формой, нужно выполнить ф-ю is_valid!!!
        elif do_comment_photo_form.is_valid():
            vk_group_id = do_comment_photo_form.cleaned_data.get('vk_group_id')  # потому что словарь!
            message = do_comment_photo_form.cleaned_data['message']  # потому что словарь!
            # message = do_comment_photo_form.message
            print('тут что-то происходит, а не должно при нажатии кнопки загрузить', vk_group_id, message)
            # api, postgres_con, postgres_cur = get_important_params()
            # generator_for_commenting = do_comment_photo(
            # api, postgres_con, postgres_cur, vk_group_id, consider_user_sex=True, is_run_from_interface=True)
            # todo костыльные внутренние серверы блин

            sock = socket.socket()
            sock.connect(('localhost', 9092))
            # sock.send(b'start_generator')
            # data = sock.recv(10244)
            open_signal = bytes('start_commenting_photo', encoding='utf8')
            # print(message)
            sock.send(open_signal)
            data = sock.recv(1024)
            if data == b'start_commenting_photo_resp':
                parameters = vk_group_id + ', ' + message
                parameters = bytes(parameters, encoding='utf8')
                sock.send(parameters)
                context['status_for_start_of_posting_ava_comment'] = \
                    do_comment_photo_form.status_for_start_of_posting_ava_comment
                data = sock.recv(1024)
                if data == b'cought_exeption':
                    context['status_for_cought_exeption'] = '!!!!'

            print(data)
            if data == 'end':
                # sock.close()
                context['status_for_finish_of_posting_ava_comment'] = \
                    do_comment_photo_form.status_for_finish_of_posting_ava_comment
            elif data == 'unknown_parameter':
                sock.close()

            '''for gen_result in generator_for_commenting:
                if gen_result == 'handling_exception':
                    #todo всплывающее окно нужно ли всплывающее окно???
                    inputed_captcha = input()
                    print('принята капча', inputed_captcha)
                    generator_for_commenting.send(inputed_captcha)
            '''
        elif do_wall_post_form.is_valid():
            # ветка для постов на стенку
            # метод cleaned data возвращает словарь!
            vk_group_id_for_wall_post = do_wall_post_form.cleaned_data.get('vk_group_id_for_wall_post')
            wall_post = do_wall_post_form.cleaned_data['wall_post'] # потому что словарь!
            # todo подумать на счёт портов
            sock = socket.socket()
            sock.connect(('localhost', 9093))
            open_signal = bytes('start_posting_wall_comments', encoding='utf8')
            # print(message)
            sock.send(open_signal)
            data = sock.recv(1024)
            print(data)
            logger.info('{}: data'.format(datetime.time()))
            if data == b'start_posting_wall_comments_resp':

                attachments = str(['audio-41360940_426516897',
                                   'audio-41360940_327478545',
                                   'audio-41360940_456239024',
                                   'audio-41360940_456239025',
                                   'photo-41360940_378305307'])
                print(vk_group_id_for_wall_post, wall_post, attachments)

VKSpammer/VKSpam_djg/templates/VKSpam_djg/distr_to_privat.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Рассылка в личку</title>
</head>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'VKSpam_djg/style.css' %}" />

{% include "VKSpam_djg/navigation.html" %}

<div>
    <form enctype="multipart/form-data"  action="{% url 'VKSpam_djg:distr_to_privat' %}" method="post">
        {% csrf_token %}
        {{ do_privat_message_form.as_p }}
            <input type="submit" value="начать отправку в личку">

        {% if status_for_start_of_privat_distr  %}
            <ul>
                <h2> {{status_for_start_of_privat_distr}} </h2>
                </ul>
        {% endif %}

        {% if status_for_finish_of_privat_distr %}
            <ul>
                <h2> {{status_for_finish_of_privat_distr}} </h2>
                </ul>
        {% endif %}
    </form>

    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:distr_to_privat' %}" method="post">
        {% csrf_token %}
        <p> Отправка в личку в режиме "mультисендер" </p>
        {{ do_privat_multisender_sending_mess_form.as_p }}
            <input type="submit" value="начать отправку">
    </form>
</div>

<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:make_distribution_to_friends_private' %}" method="post">
        {% csrf_token %}
     {{ send_messages_to_friends_private_form.as_p }}
        <input type="submit" value="начать отправку сообщений в личку друзьям " />

        {% if status_for_start_of_privat_distr  %}
            <ul>
                <h2> {{ status_for_start_of_privat_distr }} </h2>
                </ul>
        {% endif %}

        {% if  status_for_finish_of_privat_distr %}
            <ul>
                <h2> {{ status_for_finish_of_privat_distr }} </h2>
                </ul>
        {% endif %}
    </form>
</div>

<p> Invite-Рассылка в личку пользователям "целевой" группы (Горький) </p>
<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:make_distribution_to_aim_group_users' %}" method="post">
        {% csrf_token %}
     {{ send_messages_to_aim_group_user_form.as_p }}
        <input type="submit" value="начать отправку сообщений в личку пользователям Горького" />

        {% if status_for_start_of_privat_distr  %}
            <ul>
                <h2> {{ status_for_start_of_privat_distr }} </h2>
                </ul>
        {% endif %}

        {% if  status_for_finish_of_privat_distr %}
            <ul>
                <h2> {{ status_for_finish_of_privat_distr }} </h2>
                </ul>
        {% endif %}
    </form>
</div>

<p> Invite-Рассылка в личку посредством имитации работы в браузере </p>
<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:make_distribution_in_privat_through_fake_browser' %}" method="post">
        {% csrf_token %}
     {{ make_distribution_through_fake_browser_form.as_p }}
        <input type="submit" value="начать отправку сообщений в личку посредством фейкового браузера" />

        {% if status_for_start_of_privat_distr  %}
            <ul>
                <h2> {{ status_for_start_of_privat_distr }} </h2>
                </ul>
        {% endif %}

        {% if  status_for_finish_of_privat_distr %}
            <ul>
                <h2> {{ status_for_finish_of_privat_distr }} </h2>
                </ul>
        {% endif %}
    </form>
</div>

VKSpammer/VKSpam_djg/templates/VKSpam_djg/distr_to_walls.html
<!DOCTYPE html>
<html>
    <head>
        <title>VKCommunicator/distr_to_avas</title>

    </head>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'VKSpam_djg/style.css' %}" />


{% include "VKSpam_djg/navigation.html" %}   <!-- так включаем другой шаблон в этот шаблон-->
<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:distr_to_walls' %}" method="post">
        {% csrf_token %}
     {{ do_wall_post_form.as_p }}
        <input type="submit" value="начать постинг" />

        {% if status_for_start_of_wall_post  %}
            <ul>
                <h2> {{status_for_start_of_wall_post}} </h2>
                </ul>
        {% endif %}

        {% if status_for_finish_of_wall_post %}
            <ul>
                <h2> {{status_for_finish_of_wall_post}} </h2>
                </ul>
        {% endif %}
    </form>

        {% include "captcha_input_form.html" with  cif="url 'VKSpam_djg:distr_to_walls'" %}
</div>

VKSpammer/VKSpam_djg/templates/VKSpam_djg/insert_to_platform_result.html
<h1> спасибо за использование продукта!<h1>
    <h2> Абоненты, которым доставлены сообщения, подписаны на подписки <h2>


{% if result_of_inserter  %}
    <p> {{ error }} {{result_of_inserter}} </p>
    <p> </p>
    <p> </p>
    <p> </p>

        {% else %}
        <p> {{error }}  </p>
        <p> {{ camp_id_forGMT_3 }} </p>
        <p> {{ camp_id_forGMT_6 }}</p>
        <p> {{ camp_id_forGMT_11 }}</p>
{% endif %}

VKSpammer/VKSpam_djg/templates/VKSpam_djg/navigation.html
<ul id="navigation">
    <li>
        <a href="=/VKCommunicator/start_campaign"> Настройка рассылок </a>
    </li>
    <li>
        <a href="/VKCommunicator/"> Main Page! </a>
    </li>
    <li>
        <a href="/VKCommunicator/works_with_groups/"> Работа с сообществами </a>
    </li>
    <li>
        <a href="/VKCommunicator/statistics/"> Статистика </a>
    </li>
    <li>
        <a href="/VKCommunicator/distr_to_avas/"> Рассылка по аватаркам </a>
    </li>
    <li>
        <a href="/VKCommunicator/distr_to_walls/"> Рассылка по стенам </a>
    </li>
    <li>
        <a href="/VKCommunicator/distr_to_privat/"> Рассылка в личку</a>
    </li>
    <li>
        <a href="/VKCommunicator/sender_bots/"> Редактирование сендеров </a>
    </li>
    <li>
        <a href="/VKCommunicator/working_with_aim_group"> Работа с целевой группой </a>
    </li>
</ul>

VKSpammer/VKSpam_djg/templates/VKSpam_djg/result_search_file.html
<h1> спасибо за использование продукта!<h1>
    <h2> теперь Вы можете запустить кампанию (проверьте, что скрипт уже не запускается автоматически, посредством кронов<h2>


{% if count_of_wrong_number  %}
    <p> {{ error }} {{count_of_wrong_number}} </p>
        {% else %}
        <p> все номера успешно загружены</p>
{% endif %}

VKSpammer/VKSpam_djg/templates/VKSpam_djg/results.html
<h1>{{ subscriber_instance_object.transaction }} </h1>

VKSpammer/VKSpam_djg/templates/VKSpam_djg/sender_bots.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Боты для отправки</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'VKSpam_djg/style.css' %}" />

{% include "VKSpam_djg/navigation.html" %}

<ul>
    <div>
        <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:get_set_of_tokens' %}" method="post">
            {% csrf_token %}
            {{ get_set_of_tokens_form }}
            {{ get_set_of_tokens_form.finish_of_getting_tokens}}
            <input type="hidden" name="ask_set_of_token_btn" value="True">
            <input type="submit" value="Собрать токены">
        </form>
    </div>

    <div>
        <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:add_bots_to_eachother_friends' %}" method="post">
            {% csrf_token %}
            {{ add_bots_in_each_other_friend_form }}
            {{ add_bots_in_each_other_friend_form.finish_of_adding_bots_to_friends }}
            <input type="hidden" name="add_bots_to_eachother_friend_btn" value="True">
            <input type="submit" value="AddToFriedsEachOther">
        </form>
    </div>
    <div>
        <form enctype="multipart/form-data"
              action="{% url 'VKSpam_djg:get_sender_bots_notifications_and_sent_to_telegram' %}" method="post">
            {% csrf_token %}
            {{ get_bots_notifications_form }}
            <input type="hidden" name="get_notifications_btn" value="True">
            <input type="submit" value="GetBotsNotifications">
            </form>
    </div>

{% if bots_senders %}
    <table>
        <tr>
            <th>
                Фамилия
            </th>
            <th>
                Имя
            </th>
            <th>
                Логин ВК
            </th>
            <th>
                Пароль ВК
            </th>
            <th>
                Заблокирован ли ?
            </th>
            <th>
                Авторизоваться!
            </th>
        </tr>
{% for bot in bots_senders %}
    <tr>
        <td> {{bot.surname}} </td>
        <td> {{bot.name}} </td>
        <td> {{bot.vk_login}} </td>
        <td> {{bot.vk_password}} </td>
        <td> {{bot.is_blocked }}</td>
        <td>
            <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:bots_senders' %}" method="post" class="autorise">
            {% csrf_token %}
            {{autorisation_form}}
            <input type="hidden" name="autorisation" value={{bot.id}}>
            <input type="submit" value="авторизоваться">
            </form>
        </td>
    </tr>
{% endfor %}
    </table>
{%endif%}
    </ul>
</body>
</html>

VKSpammer/VKSpam_djg/templates/VKSpam_djg/statistics.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'VKSpam_djg/style.css' %}" />

{% include "VKSpam_djg/navigation.html" %}

<div>
<form enctype="multipart/form-data" action="{% url 'VKSpam_djg:statistics' %}" method="post" >
        {% csrf_token %}
     {{ get_statistics_form.as_p }}
        <input type="submit" value="получить статистику по аватаркам"  class="button button-green"   />
    </form>
</div>

{% if  count_of_photo_comment_posted %}
    <ul>
        <p>  Пользователям группы {{ group_id }} отправлено
             {{ count_of_photo_comment_posted  }} комментариев к аватаркам
            </p>
        </ul>
{% endif %}

{% if count_of_privat_message_sent %}
    <ul>
        <p>  Пользователям группы {{ group_id }} отправлено
             {{ count_of_privat_message_sent  }} cooбщений в личку
            </p>
        </ul>
{% endif %}



{% if count_of_wall_post_sent %}
    <ul>
        <p>  Пользователям группы {{ group_id }} отправлено
             {{ count_of_wall_post_sent  }} постов на стену
            </p>
        </ul>
{% endif %}

{% if count_of_group_subscribers %}
    <ul>
        <p>  Всего в базе данных содержится  {{ count_of_group_subscribers  }} пользователей группы
            {{ group_id }}
            </p>
        </ul>
{% endif %}

{% if count_of_possible_ava_comment %}
    <ul>
        <p>  Разрешено комментировать аватарки у {{ count_of_possible_ava_comment }} пользователей группы
            {{ group_id }}
            </p>
        </ul>
{% endif %}


{% if count_of_possible_privat_message %}
    <ul>
        <p>  Разрешено отслылать сообщения в личку у {{ count_of_possible_privat_message }} пользователей группы
            {{ group_id }}
            </p>
        </ul>
{% endif %}

VKSpammer/VKSpam_djg/templates/VKSpam_djg/window_for_captcha.html
<div>

    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:window_for_captcha' %}" method="post">
        {% csrf_token %}
        {{ enter_captcha_form }}
            <input type="submit" value="отправить капчу">
        </form>
  </div>

VKSpammer/VKSpam_djg/templates/VKSpam_djg/working_with_aim_group.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'VKSpam_djg/style.css' %}" />
{% include "VKSpam_djg/navigation.html" %}

{% if get_updates_of_aim_group %}
<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:working_with_aim_group' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="добавить новых пользователей группы" class="button button-green">
    </form>

</div>
{% endif %}

{% if status_for_getting_subscribers_of_aim_group %}
    <div>
        <p> {{ status_for_getting_subscribers_of_aim_group }} </p>
    </div>
{% endif %}


{% if get_aim_group_wall_posts %}
<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:get_aim_group_wall_posts' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="получить посты со стены группы" class="button button-green">
    </form>

</div>
{% endif %}

{% if status_for_get_aim_group_wall_posts %}
    <div>
        <p> {{ status_for_get_aim_group_wall_posts }} </p>
    </div>
{% endif %}



<div>

    <form enctype="multipart/form-data"
          action="{% url 'VKSpam_djg:like_aim_group_wall_post_through_fake_browser' %}"
          method="post">
        {% csrf_token %}
        {{ like_aim_group_posts_form.as_p }}
        <input type="submit" value="пролайкать посты" class="button button-green">
    </form>

    <!--{% if like_aim_group_wall_post_through_fake_browser %}-->
        <!--<ul>-->
            <!--<h2> {{ status_for_start_of_privat_distr }} </h2>-->
        <!--</ul>-->
    <!--{% endif %}-->
</div>


{% if status_like_aim_group_wall_post_through_fake_browser %}
    <div>
        <p> {{ status_like_aim_group_wall_post_through_fake_browser }} </p>
    </div>
{% endif %}

VKSpammer/VKSpam_djg/templates/VKSpam_djg/works_with_groups.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'VKSpam_djg/style.css' %}" />

{% include "VKSpam_djg/navigation.html" %}

<div>
    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:works_with_groups' %}" method="post" >
        {% csrf_token %}
     {{ get_ava_info_and_photo_settings_form.as_p }}
        <input type="submit" value="собрать настройки аватарок"  class="button button-green"   />
    </form>
    </div>
<div>

    <form enctype="multipart/form-data" action="{% url 'VKSpam_djg:works_with_groups' %}" method="post" >
        <p>работа с настройками аватарок в режиме "мультисендер"</p>
        {% csrf_token %}
     {{ multisender_get_ava_info_and_photo_setting_form.as_p }}
        <input type="submit" value="собрать в мультисендере настройки аватарок"  class="button button-green"   />
    </form>
    </div>